guard :kitchen, concurrency_level: 1, destroy_on_reload: false, destroy_on_exit: true do
  watch(%r{^attributes/(.+)\.rb$})
  watch(%r{^definitions/(.+)\.rb$})
  watch(%r{^files/(.+)})
  watch(%r{^libraries/(.+)\.rb$})
  watch(%r{^providers/(.+)\.rb$})
  watch(%r{^resources/(.+)\.rb})
  watch(%r{^recipes/(.+)\.rb$})
  watch(%r{^templates/(.+)})
  watch(%r{^Berksfile$})
  watch(%r{^metadata\.rb$})
  watch(%r{^test/.+})
  watch(%r{^.kitchen(\.local)?.yml$})
end
